FROM devlikeapro/waha:latest
ENV WHATSAPP_API_SERVER=http://0.0.0.0:3000
ENV WAHA_DASHBOARD_ENABLED=true
ENV WAHA_DASHBOARD_USERNAME=admin
ENV WAHA_DASHBOARD_PASSWORD=flowdesk2024
ENV DEBUG=false
EXPOSE 3000